### ISSUE TITLE
AttributeError: 'objc.native_selector' object has no attribute 'parent'

### ISSUE THREAD

**Issue by weiweihuanghuang** [jenskutilek/RedArrow-Glyphs#23]
I get this error sometimes now, not sure what triggers it atm
```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1145, in drawForegroundForLayer_options_
  File "~/Library/Application Support/Glyphs/Plugins/RedArrow.glyphsReporter/Contents/Resources/plugin.py", line 104, in foreground
    self._updateOutlineCheck(layer)
  File "~/Library/Application Support/Glyphs/Plugins/RedArrow.glyphsReporter/Contents/Resources/plugin.py", line 214, in _updateOutlineCheck
    self.options["grid_length"] = layer.parent.parent.gridLength
AttributeError: 'objc.native_selector' object has no attribute 'parent'
```

**Comment by weiweihuanghuang** [comment]
oops started getting this again
